Django/mySite/login/urls.py
'''
Created on 22/apr/2013

@author: lowcoupling
'''
from django.conf.urls import patterns, url

from login import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'login', views.login_view, name='login'),
    url(r'logout', views.logout_view, name = 'logout'),
)

Django/mySite/mySite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^authentication/', include('login.urls')),
    url(r'^authenticaion/logout', include('login.urls')),
)

# 

Django/mySite/polls/urls.py
'''
@author: lowcoupling
'''
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote_view, name='vote'),
)

Django/mySite/login/models.py
from django.db import models

# Create your models here.

Django/mySite/polls/models.py
from django.db import models

# Create your models here.
class Poll (models.Model):
    question = models.CharField(max_length=200);
    pub_date = models.DateTimeField('date published');

class Choice(models.Model):
    poll = models.ForeignKey(Poll);
    text = models.CharField(max_length=200);
    votes = models.IntegerField(default=0);

Django/mySite/login/views.py
# Create your views here.
from django.contrib.auth import authenticate, login
from django.shortcuts import render_to_response
from django.shortcuts import redirect
from django.template import RequestContext 
from django.contrib.auth import logout

def index(request):
    if request.GET.has_key('next'):
        print request.GET['next']
    return render_to_response('login/index.html', {'next':request.GET['next']}, context_instance=RequestContext(request))

def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            if request.POST.has_key('next'):
                return redirect(request.POST['next'])
            return render_to_response('login/response.html', {'result':1}, context_instance=RequestContext(request))
        else:
            return render_to_response('login/response.html', {'result':2}, context_instance=RequestContext(request))
    else:
        return render_to_response('login/response.html', {'result':3}, context_instance=RequestContext(request))

def logout_view(request):
    logout(request)
    return redirect('/polls')
 

Django/mySite/polls/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from polls.models import Poll
from polls.models import Choice
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse


#see https://docs.djangoproject.com/en/dev/topics/auth/
@login_required
def index(request):
    latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
    return render_to_response('polls/index.html', {'latest_poll_list':latest_poll_list}, context_instance=RequestContext(request))

@login_required
def detail(request, poll_id):
    try:
        poll = Poll.objects.get(pk=poll_id)
    except Poll.DoesNotExist:
        raise Http404
    return render(request, 'polls/detail.html', {'poll': poll})

def vote_view(request,poll_id):
    print poll_id
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        print "this is bad!"
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,))) 

@login_required
def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})

    

Django/mySite/login/templates/login/index.html
{% load staticfiles %}

<title>Project Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
 	  <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 400px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }
  
    </style>
 
     <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css">
   
     
      </head>

  <body>
  <div class="container">
      <form class="form-signin" action="./login" method="post"> 
        {%csrf_token%}
        <div class="row" style="text-align:center">
        <h2 class="form-signin-heading">Please sign in</h2>
        </div>
        <div class="row"  style="text-align:center">
        <input type="text" class="input-block-level" name="username" placeholder="Username">
        </div>
        <div class="row"  style="text-align:center">
        <input type="password" class="input-block-level" name="password" placeholder="Password">
        </div>
        {% if next %}
        <input type="hidden" name="next"value="{{next}}">
        {% endif %}
       	<div class="row"  style="text-align:center">
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
        </div>
      </form>

    </div> <!-- /container -->
    
    
</body>
</html>

Django/mySite/login/templates/login/response.html
{% if result == 1 %}
Succesful Authentication
{% endif %}
{% if result == 2 %}
Inactive User
{% endif %}
{% if result == 3 %}
Authentication Failed
{% endif %}

Django/mySite/polls/templates/polls/base_generic.html
{% load url from future %}
<html lang="en">
  <head>
   
    <meta charset="utf-8">
    <title>Project Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      
      .form-poll {
        max-width:640px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
   
      }
      .form-poll .form-poll-heading,
      .form-poll .radio {
        margin-bottom: 10px;
        
      }
      .form-poll input[type="text"],
      .form-poll input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }
    </style>
    
  	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css">
    </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container ">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/polls">Polls example</a>
        </div>
        <div class="navbar-collapse collapse">
          {% if user.is_authenticated%}
           <form class="navbar-form navbar-right" action="/authentication/logout">
          <button type="submit" class="btn btn-primary">Sign out</button>
          </form>
          {%else%}
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
          </form>
        {%endif%}
        </div><!--/.navbar-collapse -->
      </div>
    </div>
    
    
    <div class="container theme-showcase">
      {% block content %}{% endblock %}
    </div> <!-- /container -->
    
    
</body>
</html>

Django/mySite/polls/templates/polls/detail.html
{% extends "polls/base_generic.html" %}
{% block content %}
<div class="row">

	{% if poll %}
		<div class="page-header">
        <h2 class="">{{poll.question}}</h2>
        </div>
    	<form action="/polls/1/vote/" method="post">
		{% csrf_token %}
        <div class="form-group">
  		{% for choice in poll.choice_set.all %}
 
    		<div class="radio" >
  			<label >
    		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
			 {{ choice.text }}
       		</label>
			</div> 
		{% endfor %}
        </div>
        
    	<div class="form-group " style="margin-top:10px">
      	<button type="submit" class="btn btn-default">Submit</button>
    
 		</div>
		</form>
		</div>
 	{% else %}
   			 <p>No info about this poll</p>
	{% endif %}
</div>
{% endblock %}

Django/mySite/polls/templates/polls/index.html
{% extends "polls/base_generic.html" %}
{% block content %}
<div class="row">
		{% if latest_poll_list %}
    			<div class="page-header"> <h2> Latest Polls </h2></div>
    		<ul>
    			
    			{% for poll in latest_poll_list %}
        		<li><a style="color:black" href="/polls/{{ poll.id }}/"> {{ poll.question }} </a></li>
    			{% endfor %}
   			 </ul>
		{% else %}
   			 <p>No polls are available.</p>
		{% endif %}
 </div>
{%endblock%}

Django/mySite/polls/templates/polls/results.html
{% load url from future %}
<html lang="en">
  <head>
   <script type="text/javascript" src="https://www.google.com/jsapi"></script>
   <script type="text/javascript">
     var data;
     var chart;
     // Load the Visualization API and the piechart package.
     google.load('visualization', '1', {'packages':['corechart']});
     // Set a callback to run when the Google Visualization API is loaded.
     google.setOnLoadCallback(drawChart);

     // Callback that creates and populates a data table,
     // instantiates the pie chart, passes in the data and
     // draws it.
     function drawChart() {

     // Create our data table.
     data = new google.visualization.DataTable();
     data.addColumn('string', 'Choice');
     data.addColumn('number', 'Votes');
     data.addRows([
     {% for choice in poll.choice_set.all %}
    ['{{ choice.text }}',{{ choice.votes }}]{% if not forloop.last %},{% endif %}
{% endfor %}]);

     // Set chart options
     var options = {'title':'Poll Results',
                       'width':400,
                       'height':300};

     // Instantiate and draw our chart, passing in some options.
     chart = new google.visualization.PieChart(document.getElementById('chart_div'));
     google.visualization.events.addListener(chart, 'select', selectHandler);
        chart.draw(data, options);
     }

      function selectHandler() {
        var selectedItem = chart.getSelection()[0];
        var value = data.getValue(selectedItem.row, 0);
        alert('The user selected ' + value);
      }

    </script> 
    
    <meta charset="utf-8">
    <title>Project Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
      
      .form-poll {
        max-width:640px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
   
      }
      .form-poll .form-poll-heading,
      .form-poll .radio {
        margin-bottom: 10px;
        
      }
      .form-poll input[type="text"],
      .form-poll input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }
    </style>
    
  	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap-theme.min.css">
    </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container ">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/polls">Polls example</a>
        </div>
        <div class="navbar-collapse collapse">
          {% if user.is_authenticated%}
           <form class="navbar-form navbar-right" action="/authentication/logout">
          <button type="submit" class="btn btn-primary">Sign out</button>
          </form>
          {%else%}
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
          </form>
        {%endif%}
        </div><!--/.navbar-collapse -->
      </div>
    </div>
    
    
    <div class="container theme-showcase">


<h1>{{ poll.question }}</h1>
<div class="row">
<div style="margin-top:15px" class="col-sm-4 col-md-4 col-lg-4">
<ul>
<h4> What people voted: </h4>
<div style="margin-left:20px">
{% for choice in poll.choice_set.all %}
    <li><b>{{ choice.text }}</b>: {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</div>
</ul>
</div>
<div class="col-sl-4 col-md-4 col-lg-4">
 <div id="chart_div" style="width:400; height:300"></div>
 </div>
<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

  </div>
  </div> <!-- /container -->
    
    
</body>
</html>